name: CI
on:
  push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      run: ./build.sh && ./esh build.esh runTests=true
  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      run: ./build.sh && ./esh build.esh runTests=true
  build-win32:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        cl.exe esh.c /Wall /wd4201 /wd4242 /wd4255 /wd4267 /wd4456 /wd4668 /wd4710 /wd4711 /wd4774 /wd4820 /wd4996 /wd5045
        esh.exe build.esh runTests=true
