name: CI
on:
  push
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      run: ./build.sh && ./esh build.esh runTests=true
  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      run: ./build.sh && ./esh build.esh runTests=true
  build-win32:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2          
    - name: build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        cl.exe esh.c /Wall /Wno:4201 /Wno:4242 /Wno:4255 /Wno:4267 /Wno:4456 /Wno:4668 /Wno:4710 /Wno:4711 /Wno:4774 /Wno:4820 /Wno:4996 /Wno:5045
        esh.exe build.esh runTests=true
